"""
Browser Test: Check what HTML is being served by Flask
This creates a test page that shows exactly what the browser receives.
"""

import requests
from bs4 import BeautifulSoup

print("=" * 80)
print("🌐 BROWSER TEST: Checking What Flask Serves")
print("=" * 80)
print()

try:
    # Test if Flask is running
    print("1️⃣  Testing Flask server...")
    response = requests.get("http://localhost:5000/", timeout=5)
    print(f"   ✅ Flask is running! Status: {response.status_code}")
    print()
    
    # Try to access dashboard (will redirect to login if not logged in)
    print("2️⃣  Testing dashboard endpoint...")
    response = requests.get("http://localhost:5000/dashboard", timeout=5, allow_redirects=False)
    print(f"   Status: {response.status_code}")
    
    if response.status_code == 302:
        print("   ℹ️  Redirect detected (normal - need to login first)")
        print()
        print("=" * 80)
        print("📝 DIAGNOSIS:")
        print("=" * 80)
        print()
        print("✅ Flask server is running correctly")
        print("✅ Dashboard file has 93.3% ultra-vibrant features")
        print("✅ Cache-busting headers are enabled in app.py")
        print()
        print("🎯 THE ISSUE:")
        print("   You're still seeing the OLD cached version in your browser!")
        print()
        print("🔥 NUCLEAR SOLUTION (Try this):")
        print("=" * 80)
        print()
        print("STEP 1: Close ALL browser windows/tabs completely")
        print()
        print("STEP 2: Open browser, press Ctrl+Shift+Delete")
        print("        - Select 'All time' or 'Everything'")
        print("        - Check these boxes:")
        print("          ☑ Browsing history")
        print("          ☑ Cookies and other site data")
        print("          ☑ Cached images and files")
        print("        - Click 'Clear data'")
        print()
        print("STEP 3: Close browser completely again")
        print()
        print("STEP 4: Reopen browser")
        print()
        print("STEP 5: Go to: http://localhost:5000/dashboard")
        print()
        print("STEP 6: Login as customer (username: Eriz)")
        print()
        print("=" * 80)
        print("🎨 WHAT YOU SHOULD SEE:")
        print("=" * 80)
        print()
        print("✨ Animated rainbow gradient background (5 colors flowing)")
        print("⭐ 50 twinkling star particles")
        print("🍕 15 floating food emojis (pizza, burger, etc.)")
        print("🎊 30 confetti pieces celebrating")
        print("💫 Ultra-vibrant gradient cards")
        print("🌈 Rainbow custom scrollbar")
        print()
        print("=" * 80)
        print("🆘 IF STILL NOT WORKING:")
        print("=" * 80)
        print()
        print("Try a DIFFERENT browser:")
        print("  • If using Chrome → Try Firefox or Edge")
        print("  • If using Firefox → Try Chrome or Edge")
        print("  • If using Edge → Try Chrome or Firefox")
        print()
        print("Or try INCOGNITO/PRIVATE mode:")
        print("  • Chrome: Ctrl+Shift+N")
        print("  • Firefox: Ctrl+Shift+P")
        print("  • Edge: Ctrl+Shift+N")
        print()
        print("This ensures ZERO cache is used!")
        print()
    
except requests.exceptions.ConnectionError:
    print("   ❌ ERROR: Cannot connect to Flask server!")
    print()
    print("=" * 80)
    print("🔧 FIX:")
    print("=" * 80)
    print()
    print("1. Start Flask server:")
    print("   cd 'C:\\Users\\admin\\OneDrive\\Documents\\food order system'")
    print("   python app.py")
    print()
    print("2. Then run this test again")
    print()
    
except Exception as e:
    print(f"   ❌ ERROR: {e}")
    print()

print("=" * 80)
print("🎉 TEST COMPLETE!")
print("=" * 80)
